name: Lint and Type

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - run: pnpm install
      - name: Prettier
        run: pnpm prettier:ci
      - name: Lint
        run: pnpm eslint:ci
      - name: Type
        run: pnpm pretest