name: Test Old TypeScript

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

jobs:
  test_matrix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        typescript:
          - 4.8.4
          - 4.7.4
          - 4.6.4
          - 4.5.5
          - 4.4.4
          - 4.3.5
          - 4.2.3
          - 4.1.5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - run: pnpm install --frozen-lockfile --check-files
      - run: pnpm build
      - name: Patch for Old TS
        run: |
          sed -i~ 's/\/\/ @ts-expect-error.*\[LATEST-TS-ONLY\]//' tests/*.tsx
          sed -i~ 's/"target":/"skipLibCheck":true,"target":/' tsconfig.json
          sed -i~ 's/"exactOptionalPropertyTypes": true,//' tsconfig.json
          sed -i~ 's/"rezustand": \["\.\/src\/index\.ts"\],/"rezustand": [".\/dist\/index.d.ts"],/' tsconfig.json
          sed -i~ 's/"rezustand\/\*": \["\.\/src\/\*\.ts"\]/"rezustand\/*": [".\/dist\/*.d.ts"]/' tsconfig.json
          sed -i~ 's/"include": .*/"include": ["src\/types.d.ts", "dist\/**\/*", "tests\/**\/*"],/' tsconfig.json
          pnpm json -I -f package.json -e "this.resolutions={}; this.resolutions['@types/node']='18.13.0';"
          pnpm add -D @types/node@18.13.0
      - name: Test ${{ matrix.typescript }}
        run: |
          pnpm add -D typescript@${{ matrix.typescript }}
          rm -r node_modules/parse5
          pnpm tsc --noEmit