name: Test Multiple Versions

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - run: pnpm install
      - name: Test Build # we don't have any other workflows to test build
        run: pnpm build
      - name: Test Default
        run: pnpm test:ci

  test_matrix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        react:
          - 17.0.0
          - 18.0.0
          - 18.1.0
          - 18.2.0
          - 18.3.0-next-49f741046-20230305
          - 0.0.0-experimental-49f741046-20230305
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - run: pnpm install
      - name: Test ${{ matrix.react }}
        run: |
          pnpm add -D react@${{ matrix.react }} react-dom@${{ matrix.react }}
          pnpm test:ci